version: 2
updates:
  - package-ecosystem: "dotnet:nuget"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - RakSrinaNa
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - RakSrinaNa
